### PR TITLE
Allows sorted() for GoogleDriveFile objects

### PR DESCRIPTION
**Pull request by Mottl**
Add `__le()__` function to allow `sorted()` capability for GoogleDriveFile objects.

Example:
```python
file_list = drive.ListFile({'q': "'%s' in parents and trashed=false"%id}).GetList()
for file in sorted(file_list):
    ...
```

### CODE REVIEW

**Comment by Mottl** [comment]
I signed it

**Comment by erickoledadevrel** [comment]
Sorry for the long delay getting to this PR. Can you also add a test to `test_filelist.py` for the sorting behavior?

**Comment by erickoledadevrel** [comment]
Actually, it seems like `test_file.py` would be the correct file to add the test too, since you are sorting a Python list of GoogleDriveFile, not the GoogleDriveFileList type.

**Comment by Mottl** [comment]
> Actually, it seems like `test_file.py` would be the correct file to add the test too, since you are sorting a Python list of GoogleDriveFile, not the GoogleDriveFileList type.

Seems like `test_filelist.py` is more appropriate since we use the output of `GetList()`:
```python
file_list = drive.ListFile({'q': "'%s' in parents and trashed=false"%id}).GetList()
for f in sorted(file_list):
    ...
```

**Pull request closed without merging**
